parameters:
    dynamicsite.generator.class: LisActiv\Bundle\DynamicSiteBundle\Service\DynamicSiteGeneratorService

services:
    dynamicsite.generator:
        class: %dynamicsite.generator.class%
        arguments:
            - @ezpublish.api.repository
            - @ezpublish.api.service.location
            - @ezpublish.api.service.search
            - @ezpublish.api.service.user
