parameters:
    dynamicsite.generator.class: LisActiv\Bundle\DynamicSiteBundle\Service\DynamicSiteGeneratorService

services:
    dynamicsite.generator:
        class: %dynamicsite.generator.class%
        arguments:
            - @ezpublish.api.repository
        calls:
            - [ setContainer,[ @service_container ] ]
